#声明电影购票微服务的端口号
server:
  port: 8001
#
spring:
  application:
    name: microservice-movie

#eureka客户端
eureka:
  client:
    #向eureka服务器注册
    register-with-eureka: true
    #向eureka服务器索要信息
    fetch-registry: true
    #声明eureka注册服务的url
    service-url:
      defaultZone: http://192.168.17.1:8888/eureka
    #////////////////////////////////////////////////////////////////////
    #微服务的消费方与eureka服务器的约定
    #每30秒获取一次eureka服务器的最新信息
    registry-fetch-interval-seconds: 30 #默认是30秒
